# Generated by Django 5.2 on 2025-05-01 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('current_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_company_id', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_details', models.TextField(blank=True, help_text='Detailed work experience', null=True)),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True)),
                ('education_summary', models.CharField(blank=True, help_text='e.g., BSc Computer Science', max_length=255, null=True)),
                ('education_details', models.TextField(blank=True, help_text='Detailed education history', null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills or JSON', null=True)),
                ('skill_categories', models.TextField(blank=True, help_text='Comma-separated or JSON', null=True)),
                ('languages', models.CharField(blank=True, help_text='e.g., English, Spanish', max_length=255, null=True)),
                ('interests', models.TextField(blank=True, help_text='General interests', null=True)),
                ('startup_industries', models.TextField(blank=True, help_text='Industries of interest for startups', null=True)),
                ('startup_goals', models.TextField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('courses', models.TextField(blank=True, null=True)),
                ('recommendations_count', models.PositiveIntegerField(default=0)),
                ('volunteer_experience', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
