# Generated by Django 5.2 on 2025-05-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='offers',
            field=models.TextField(blank=True, help_text='Comma-separated things user can offer', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_role_on_profile',
            field=models.BooleanField(default=False),
        ),
    ]
