# Generated by Django 5.2 on 2025-05-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_offers_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='looking_for',
            field=models.TextField(blank=True, null=True),
        ),
    ]
